[versions]
agp = "8.12.2"
kotlin = "1.9.22"
streamChat = "6.0.13"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleServices = "4.4.2"
firebaseBom = "33.4.0"
firebaseFirestoreKtx = "26.0.2"
ui = "1.9.4"

[libraries]
# Stream Chat SDK
stream-chat-client = { group = "io.getstream", name = "stream-chat-android-client", version.ref = "streamChat" }
stream-chat-state = { group = "io.getstream", name = "stream-chat-android-state", version.ref = "streamChat" }
stream-chat-offline = { group = "io.getstream", name = "stream-chat-android-offline", version.ref = "streamChat" }
stream-chat-ui-components = { group = "io.getstream", name = "stream-chat-android-ui-components", version.ref = "streamChat" }
stream-chat-compose = { group = "io.getstream", name = "stream-chat-android-compose", version.ref = "streamChat" }
stream-chat-markdown = { group = "io.getstream", name = "stream-chat-android-markdown-transformer", version.ref = "streamChat" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

